//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication42
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int id { get; set; }
        public string DName { get; set; }
        public Nullable<long> salary { get; set; }
        public Nullable<int> d_id { get; set; }
        public Nullable<System.DateTime> joining_date { get; set; }
        public Nullable<int> dept_id { get; set; }
    }
}
